### ISSUE TITLE
Integration: Gitcoin Passport

### ISSUE THREAD

**Issue by drakedanner** [FlipsideCrypto/badger#102]
https://docs.passport.gitcoin.co/gitcoin-passport-sdk/getting-started

Badge issuers may wish to use Gitcoin Passport to prevent sybil attacks.

Research needed on implementation details and business rules / level of flexibility required.

**Comment by nftchance** [comment]
After a period of research with GitCoin, we will not be implementing their false usage/existence of "DIDs"

Passport is literally an API wrapper that does nothing more than serve as a higher level of confidence that it's a person. It's a non-solution to the problem. If we find someone that has actually solved the problem we are open to implementation. 

All this does is push the line of acceptance of gameability into the farthest edges of one's network while losing all ability to truly see the measure to which someone filled the criteria.


In-bound aggregate actions nor output aggregate actions for the use of DIDs is not currently and is not planned to be a focus of Badger as it is a short-time market bubble until any of these things have genuine value. Integrations within Badger, will largely be about making ownership and usage better, not the minting of badges.
