### ISSUE TITLE
Integration: KYC Provider

### ISSUE THREAD

**Issue by drakedanner** [FlipsideCrypto/badger#103]
Could use a traditional KYC provider or a newer proof of personhood protocol.

https://docs.withpersona.com/reference/introduction

https://developers.veriff.com/#introduction

https://github.com/worldcoin/world-id-docs

https://dev.brightid.org/

**Comment by nftchance** [comment]
Thanks for this. Is there a most supported option in the market? Realistically these are all going to do the same thing so would prefer a KYC platform that:

* has a centralized point of verification
* provides an NFT in return
* allows us to check for the holding of an account bound KYC proof

The desire being that they are not just KYCing for us, and that we've merely adopted an existing network that they may already be KYCed. If they are within an organization that needs KYC, the odds are high they are in other organization that had the same or similar requirements.

Would this be the expected functionality of a KYC provider?
