### ISSUE TITLE
Inline Actions for Badger Members/Delegates

### ISSUE THREAD

**Issue by drakedanner** [FlipsideCrypto/badger#11]
Allow a user to edit the Yes/No of Member/Delegate inline instead of through the manage drawer

**Comment by masonchain** [comment]
What does this look like? Just a single change transaction?

Or more in the line of opening an edit mode that lets you select checkboxes and then run the tx with selected objects?

**Comment by nftchance** [comment]
Veto modal or another drawer. Yes please just a literal inline action.

**Comment by drakedanner** [comment]
Pattern could be:

Click Yes/No in line and add that to the view in the manage drawer. 

Clicking the button would queue the action and then clicking Update let's me execute all tx or execute them one by one similar to Velodrome reward claims

**Comment by nftchance** [comment]
Putting this one on-hold as it will have technical dependencies to make this experience better. This will be revisited after Data tables.

**Comment by nftchance** [comment]
Resolving this as close as future designs have this covered and will piece out individually rather than as an inline-functions addition.
