### ISSUE TITLE
Feature: Organization Level OFAC Compliance

### ISSUE THREAD

**Issue by nftchance** [FlipsideCrypto/badger#110]
**Under no circumstances will the base layer (primitive) of Badger be gated or an on-chain limitation. At most, this will be an opt-in feature to allow specific Organizations the ability to gatekeep who their holders are.**

**Comment by drakedanner** [comment]
Love this.

**Comment by nftchance** [comment]
Is closed as is not something that will be found inside Badger. An organization that wants to block OFAC would need to build that system. Badger wears liability with a half-solution, thus no solution is provided here as complete customizability is maintained without negatively impacting anyone.
