### ISSUE TITLE
Feature: Destroy Organization

### ISSUE THREAD

**Issue by drakedanner** [FlipsideCrypto/badger#120]
Organization owner can "Destroy Organization"

This will:
- revoke all badges from all members 
- remove managers from all badges
- transfer badge ownership to 0x00...0000

**Comment by jms1192** [comment]
Yes, I would like this to be addressed

**Comment by nftchance** [comment]
Appreciate you pitching in here @jms1192 -- This feature is currently planned for v7.

Is the functionality you want the same as below?

> This will:
> revoke all badges from all members
> remove managers from all badges
> transfer badge ownership to 0x00...0000

**Comment by jms1192** [comment]
and for the org to not show up on the front end

**Comment by nftchance** [comment]
> and for the org to not show up on the front end

Noted! Will make sure to ping you when this update goes live :)

**Comment by nftchance** [comment]
Closing as is resolved by #13 and #42 that are soon to be implemented.
