### ISSUE TITLE
Bug: Cat Collection Images are Infuriating

### ISSUE THREAD

**Issue by drakedanner** [FlipsideCrypto/badger#124]
Often, the app will take a long while to load the collection images and shows Cats. It's frustrating.

![image](https://user-images.githubusercontent.com/11461756/198919027-23a21366-7f3f-4f3d-b4b2-55c34798f1d8.png)

These are awful UX. Can we please prioritize?

**Comment by jms1192** [comment]
Yes, I would like this to be addressed

**Comment by nftchance** [comment]
Fixed in #107 -- Will be merged shortly!

Have recorded your +1 🥳
