### ISSUE TITLE
Feature: Front-end Instant Feature Determination

### ISSUE THREAD

**Issue by nftchance** [FlipsideCrypto/badger#132]
Specific versions of the contract have unique features/certain features that cannot be accessed on specific versions. We need to add support to automatically hide/show features given the Organizations version.

**Comment by masonchain** [comment]
Should be fairly simple. A compiled list of the differences as well for reference would make it even easier. 

Can have contract hooks and each page just be a controller for the relevant version's child forms/interfaces.

**Comment by nftchance** [comment]
Okay, awesome. Had been worried about this on the front end so good to hear it doesn't seem too bad to you. Going to let you take care of this then :)
