### ISSUE TITLE
Fix: Front-End API Integration

### ISSUE THREAD

**Issue by nftchance** [FlipsideCrypto/badger#133]
Right now, the API integration on the front end is setup incorrectly, resulting in stale data overwriting newer data. Additionally, due to the existing setup, if an organization has 5,000 members, it will expect all 5,000 members to be posted.

Most importantly, though, due to this current setup, balances cannot synchronously be tracked.

**Comment by masonchain** [comment]
I had this stale data on the front end concern before we launched the site. Is removing and adding M2M relationships (User from Badge users) possible with the current model/serializer methods? If so I could not figure it out when implementing (just checked and that was less than 3 weeks ago holy)

**Comment by nftchance** [comment]
> (just checked and that was less than 3 weeks ago holy)

o.m.g.

To all these questions, no. Will require a significant refactor, but will be nice and breezy been marinating for a week now.
