### ISSUE TITLE
Feature: archive organization confirmation

### ISSUE THREAD

**Issue by drakedanner** [FlipsideCrypto/badger#144]
I know this isn't ~on-chain but it's a little too easy to use the Danger Zone right now. Can we add a wallet signature as a second check?

**Comment by masonchain** [comment]
Good point. Intended to add this but ran out of time before the launch this morning.

Not quite sure it should be a signature or just a confirm modal but it definitely should be gated behind another click for security.

**Comment by nftchance** [comment]
No! Critically veto.

They are already signed in. There has already been a signature.
