### ISSUE TITLE
Feature: Badge Archiving

### ISSUE THREAD

**Issue by masonchain** [FlipsideCrypto/badger#146]
Organizational archiving is functional, but Badge archiving is not. There is the commented-out code in the BadgeForm/BadgeDangerZone files that does effectively set the badge to is_active = false. 

However, with the way the front end is currently managing data, the high-level UserData is the source of truth for everything. This means that badges and orgs are being correctly filtered out if not active, but if we get the badge from the orgs that come from userdata, the !is_active badges are still present.

Although addressable via the API, I believe this to be probably better sorted out on the front end. It would be nice to implement a caching type system for orgcontext that once a get request pulls down at org it stores it in the cache, and can be directly altered from there. The one concern I have is that by currently relying on just the userdata context object to be the source of truth, we'd have to make sure we are keeping both userdata context and orgdata context updated to the same degree.

Too tired to solve this now but dumping thoughts.

**Comment by nftchance** [comment]
Please, no further bandaids. Proper implementations only please, stacking up technical debt for no reason.
