### ISSUE TITLE
Feature: (HIGHWAY TO) THE DANGER ZONE

### ISSUE THREAD

**Issue by masonchain** [FlipsideCrypto/badger#150]
![Screen Shot 2022-11-16 at 12 32 07 PM](https://user-images.githubusercontent.com/33527785/202263867-58ed88fb-367f-4c74-8580-09adc048b96f.png)

Another feature that got bumped a version due to the crunch for launch. Most of the base code is there, including archival, however some clarity is needed. The design did not include an input field as the functionality requires, but I took a stab at it.

![Screen Shot 2022-11-16 at 12 29 28 PM](https://user-images.githubusercontent.com/33527785/202263488-2b96dce0-3b23-4eed-b9a1-acef72a4a1fc.png)

Transfer ownership is simple enough, but I'm not quite sure the best way to renounce ownership with first transferring all the assets out. Feel like there is a simple solution here I am missing but in my head it would take a transaction for every type of asset held? Does a delegatecall solve this?

**Comment by nftchance** [comment]
LOL
