### ISSUE TITLE
Fix: Editing Badge Attributes

### ISSUE THREAD

**Issue by masonchain** [FlipsideCrypto/badger#153]
Currently, our backend does not store attributes and is solely in the IPFS metadata hash. For editing, we need to have these attributes appear in the edit form.

Going to throw together a function on the front end that fetches the URI and parses the attributes and adds them to the edit form, but it would provide less friction if we could store these on the backend. @nftchance thoughts on this?

**Comment by nftchance** [comment]
Yeah didn't realize that wasn't in the backend -- I can add it, ez pz

**Comment by masonchain** [comment]
Currently functional in production by parsing the attributes from token URI. Documented the functions accomplishing this and can easily swap them out when API support arrives.

**Comment by drakedanner** [comment]
I wonder if this may also impact Manager lists.

Note from a user (Mar1na):

```When changing badge attributes (I tried changing the description a few times) it clears out any managers ```

My suspicion: 

Managers are currently stored as an approved transactor list and when editing settings of a Badge, all fields are re-established.

Can make another ticket if needed

**Comment by masonchain** [comment]
@drakedanner Appreciate the report. Was a very small issue that I took the liberty of pushing a hot fix for. Not a huge change at all, just an issue with how I was shaping the data for the transaction was actually changing the source data instead of acting as a new shaped object.

**Comment by drakedanner** [comment]
@masonchain does that mean we should expect the manager list to remain the same when editing attributes now?

If so, I'll alert the user and let them know to re-report if they have this issue again.

Thanks sir!

**Comment by masonchain** [comment]
@drakedanner Correct. Was just a small issue so slapped a bandaid on it before the webhooks refactor
