### ISSUE TITLE
Fix: Transfered Orgs Not Visible for New Owner

### ISSUE THREAD

**Issue by drakedanner** [FlipsideCrypto/badger#156]
Transferred org (PFP Deployer) from danner.eth to directdeposit.eth

https://polygonscan.com/tx/0x42caa0ac4a359ab14580c212cb5fbc09e00a2b3165fae93690b61216adb6e223

org: 0x90ffdF48A1660A2759d82c1aF78318F414B1a9b5
original owner: 0x581bef12967f06f2ebfcabb7504fa61f0326cd9a
new owner: 0x34744Dd0Fb927366228A2eAee0D142620FF26077

view from new owner

<img width="647" alt="image" src="https://user-images.githubusercontent.com/11461756/202884994-5f9c6c80-b5ce-46ab-8426-80d19ffad681.png">

view from old owner 

<img width="882" alt="image" src="https://user-images.githubusercontent.com/11461756/202885033-4c082931-6af8-49f3-a28a-3c3270478ec3.png">

(note: before logging out and back in to danner.eth, I could still see the PFP Deployer org and I could only see the item in it that danner.eth was a holder of, but not a manager of)

**Comment by nftchance** [comment]
This issue has been claimed and is in progress with PR #174.

**Comment by nftchance** [comment]
Resolved in #174
