### ISSUE TITLE
Feature: Organization Explorer

### ISSUE THREAD

**Issue by drakedanner** [FlipsideCrypto/badger#168]
Enable people to explore existing organizations without needing to log in.

They cannot do anything other than view these organizations.

They need to connect to action any organizations that they have admin control inside.

**Comment by nftchance** [comment]
This has a long list of dependencies that are going to be needed. Through the coming versions I will be working towards providing the rest of the foundation that is needed for this.

**Comment by nftchance** [comment]
Resolved by #226
