### ISSUE TITLE
fix: custom image handling

### ISSUE THREAD

**Issue by masonchain** [FlipsideCrypto/badger#227]

**Comment by nftchance** [comment]
Please fix this on Org and Badge form -- This is the one piece that I did not want to mess with.

**Comment by masonchain** [comment]
Addressed in [latest commit](https://github.com/FlipsideCrypto/badger/commit/db8521fe82f535dea3177172267e8c6b17a05f76). Unless there was a reason you wanted to read the custom image immediately that was the simple fix.
