### ISSUE TITLE
Monospaced font for addresses

### ISSUE THREAD

**Issue by masonchain** [FlipsideCrypto/badger#23]
tabular-nums lining-nums vs monospaced Roboto Mono. Tabular/lining nums does not fully solve the problem but this monospaced font also looks kind of shitty.

Either need to roll with the css fix or find a better looking mono font

![Image](https://user-images.githubusercontent.com/33527785/196523602-1bc04490-18b2-4e9b-aa43-312808d6d379.png)

![Image](https://user-images.githubusercontent.com/33527785/196523611-b2079242-e933-409f-a049-e9d5efc52bf8.png)

**Comment by nftchance** [comment]
Can you get this on a separate branch?

What about just making the table display addresses with all caps? Would prefer not to use another font just for addresses.

If anything, this would be an argument to change the brand font in my opinion however I had been really happy with the font to this point, but this is a hard stop for me.

**Comment by masonchain** [comment]
@nftchance https://github.com/FlipsideCrypto/badger/pull/29


Here's all caps Poppins with tabular nums

![Image](https://user-images.githubusercontent.com/33527785/196553456-63ea4f54-5cd4-4d4c-a2c5-0f599bc469b5.png)

**Comment by nftchance** [comment]
Yuck
