### ISSUE TITLE
Update Left Sidebar

### ISSUE THREAD

**Issue by masonchain** [FlipsideCrypto/badger#25]
Ignoring online status for now

![Image](https://user-images.githubusercontent.com/33527785/196526653-3b2e4ce8-6023-4559-88b3-fb782cbd4235.png)

**Comment by masonchain** [comment]
The contract address (and button leading to polygonscan link), and chain name has been added.

Analytics and Online statuses are on backlog until implementation.

The accordion/drawer for collapsing Orgs/Badges has not been done though and can be implemented whenever.

**Comment by nftchance** [comment]
This is being closed as it is no longer a part of the design or future versions.
