### ISSUE TITLE
Fix: Improve Error/Status Messages

### ISSUE THREAD

**Issue by masonchain** [FlipsideCrypto/badger#34]
Error messages appear in all cases they happen, but right now the language is very basic.

Inspired by [this tweet](https://twitter.com/marcoworms/status/1582382100564451330?s=46&t=BbSWfg0wJVU7EkK8GkHuFw), error messages should provide better context and an action to take for resolution, even if it just is send a support message.

Additionally, I propose that we change the Error Message component to simply a response message that serves as both Error and Success messages. The success functionality would be much lower on the priority but positive feedback on transaction/action completion would provide better UX.

**Comment by nftchance** [comment]
> Additionally, I propose that we change the Error Message component to simply a response message that serves as both Error and Success messages. The success functionality would be much lower on the priority but positive feedback on transaction/action completion would provide better UX.

Sounds good to me, send it
