### ISSUE TITLE
Delegate/Manager can Log In & Manage Badges

### ISSUE THREAD

**Issue by drakedanner** [FlipsideCrypto/badger#37]
Critical feature for go live and for MetricsDAO Season 3 scaling:

- Users with the permission to manage badges on behalf of an organization need to be able to log in and view badges they control

**Comment by nftchance** [comment]
Has been added to API support. We will move to front-end requirements before can be merged.

@masonchain will take over from here.

**Comment by masonchain** [comment]
Duplicate of [this issue/PR](https://github.com/FlipsideCrypto/badger/pull/44)

Has been implemented, just needs merging and stress testing.
