### ISSUE TITLE
Prompt User to Change Networks on All Buttons

### ISSUE THREAD

**Issue by drakedanner** [FlipsideCrypto/badger#39]
I was logged into Badger, went to another tab, switched to Optimism, came back to Badger (signed again maybe?), then tried to perform actions. I got silent errors.

Once I changed networks and refreshed, it worked

**Comment by nftchance** [comment]
The functionality of this is already implemented so not sure what happened here. Using the steps above did not reproduce the issue.

Need further detail before this can be addressed.

**Comment by drakedanner** [comment]
Re-creating this requires me to purposefully create problems for myself. Closing this unless someone else brings it up
