### ISSUE TITLE
Organization Member View

### ISSUE THREAD

**Issue by drakedanner** [FlipsideCrypto/badger#40]
I want to see how many people are in my organization, and which Badges / balances they have

**Comment by nftchance** [comment]
This is made possible by a running indexer. Balances will be supported following dependent PR merges, and then it will be in the land of getting the front-end updated to support v4.

**Comment by nftchance** [comment]
Being closed as is a dependent issue. Is covered by multi-step process of functional indexer + version 5 design update.
