### ISSUE TITLE
Feature: Batch Rescind Badge: All Badges of a Member

### ISSUE THREAD

**Issue by drakedanner** [FlipsideCrypto/badger#42]
Easy way to remove all Badges from n specific Member(s) of an organization

**Comment by drakedanner** [comment]
As an organization owner, I may want to remove an individual completely from my organization. 

This includes:
- Revoking all Badges
- Removing Manager access

Instead of going from Badge to Badge to remove the user, I want to say "get this 0x out of the org"

**Comment by nftchance** [comment]
This will be included as the working app catches up to the design. This is a very low priority, although it is a needed feature.

When implementing, we will not show a list of all users. The flow will be:

* Select badges on Organization page.
* Click `update holders`.
* Set if it is a `mint` or `revoke`.
* Enter the addresses.

-- When the address is set the field should validate that the address can have all those tokens burned.

![image](https://user-images.githubusercontent.com/22061495/197831730-88452c5b-361c-4231-b0c7-a5a9042fb756.png)

**Comment by nftchance** [comment]
Archived in preference of #41
