### ISSUE TITLE
Managers should only see the Badges that they can Manage

### ISSUE THREAD

**Issue by drakedanner** [FlipsideCrypto/badger#48]
![image](https://user-images.githubusercontent.com/11461756/197265577-49fbf237-168e-4c01-b7e7-a88ba3b1f740.png)

...6077 is a Manager for Contributors but can see Governors and Curators and gets a silent error when trying to manage those badges

**Comment by nftchance** [comment]
Nice catch 🥳 

Will get fixed up!

**Comment by masonchain** [comment]
See my PR comment. This change allows only actions that a user is permissioned to make.

Holders can see the holder table but not the Manage button or drawer. Non Holders or delegates or owners can see the badge page if directly linked, but it will not appear in their sidebar.
