### ISSUE TITLE
Feature: Show ENS Avatar or Generated/Random Image

### ISSUE THREAD

**Issue by drakedanner** [FlipsideCrypto/badger#51]
<img width="369" alt="image" src="https://user-images.githubusercontent.com/11461756/197455068-a68930b4-de61-4a2b-b208-bfb8632d9398.png">

Right now, it says I am a cat. I am not a cat

**Comment by drakedanner** [comment]
https://wagmi.sh/docs/hooks/useEnsAvatar

**Comment by forgxyz** [comment]
I disagree. Drake is a cat.

**Comment by masonchain** [comment]
> 
did you actually just link me to docs sir

![Screen Shot 2022-10-24 at 10 32 30 PM](https://user-images.githubusercontent.com/33527785/197676099-daf9e6f8-8245-48e1-beca-1087f1fb630c.png)

**Comment by masonchain** [comment]
> > https://wagmi.sh/docs/hooks/useEnsAvatar
> 
> did you actually just link me to docs sir
> 
> ![Screen Shot 2022-10-24 at 10 32 30 PM](https://user-images.githubusercontent.com/33527785/197676099-daf9e6f8-8245-48e1-beca-1087f1fb630c.png)

**Comment by nftchance** [comment]
I think this has been taken care of in #6. Please confirm.
