### ISSUE TITLE
Fix: Automatically check sum addresses in input fields

### ISSUE THREAD

**Issue by masonchain** [FlipsideCrypto/badger#57]
There are multiple instances of duplicates and errors as a result of not check summing on the front end. Needs to be fixed ASAP.

**Comment by nftchance** [comment]
While it needs to be fixed on the front end, the back end should also be formatting these double-sided here. Given, the intention was to expose our API, there is zero chance that we can get everyone to always submit.

**Comment by masonchain** [comment]
Well, probably should have kept the forced checksumming after the issue posted in MDAO.

Someone inputting a mixed case address that is not the valid checksum will cause an error. Solution is to either edit the input if the address is the right length and force the checksum, or force all lower or upper in input fields. Leaning #1 as of now.
