### ISSUE TITLE
Improve Help Text in Sidebar

### ISSUE THREAD

**Issue by drakedanner** [FlipsideCrypto/badger#7]
As it stands, the Help Sidebar is static and creates more confusion.

Additionally, the progress bar is unclear.

How many Badges am I making? You're defining the Badge, not issuing any

How do I send Badges? You can do that after you create an Org and Badge class

Can I revoke Badges?

What is Account Bound?

Can I add Delegates later?

Can I edit these descriptions or are they permanent?

**Comment by nftchance** [comment]
The new version of the `HelpSidebar` has been designed and is part of v5. The design has been caught up to v8 (supporting the current contract). The button will magically squoosh into the action header, and the vertical line will appear when it is open. Claiming back the screen's real estate for the users that do not need help.

![image](https://user-images.githubusercontent.com/22061495/196513436-dd2d412a-461c-40e3-b19b-ef712999a83d.png)
![image](https://user-images.githubusercontent.com/22061495/196513460-e26492e8-849f-444e-8d6f-7729ecea8d55.png)
