### ISSUE TITLE
Integration: Guild

### ISSUE THREAD

**Issue by drakedanner** [FlipsideCrypto/badger#9]
Provide direct links to Guild at the Organization and Badge level

**Comment by nftchance** [comment]
This will be straightforward to complete. However, there will be a process that needs to be followed here:
- [ ] Establish touch point 
- [ ] Spec sheet. 
- [ ] Callback hooks we need to offer the same ability to any partner we integrate. (What API exposure does our end need to offer for them to implement direct integration? They can do everything on-chain. However, we can additionally offer helper API functions if needed.)

(We are familiar with their API. Are we going to be able to get write access without needing to manage a rolling token?)

It will be part of v4, so we can plan on including this before the public launch if things move at the proper pace.

**Comment by nftchance** [comment]
This is being moved to v8 in order to prevent this from becoming a blocker.
