### ISSUE TITLE
Fix: Update Members UX

### ISSUE THREAD

**Issue by nftchance** [FlipsideCrypto/badger#99]
![Image](https://user-images.githubusercontent.com/22061495/197901106-5e007814-3998-429f-9e20-5b43cd60d8a6.png)

![Image](https://user-images.githubusercontent.com/22061495/197901329-17feecf2-3aa1-4a6f-bb5b-8507bcd5cd2c.png)

**Comment by masonchain** [comment]
Not sure about the info on accepted CSV, seems like "CSV" is fairly self explanatory to me -- especially with accepting CSVs with and without a header.

The rest of this is addressed in my out-of-scope PR that is linked. Address fields now have a place holder of "0x0000...", button click issue is resolved for this page. Checksumming addresses is next on my todo though but lives in another issue.
